# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties

spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    db: friosdb
    host: DB_MYSQL_DESAENV04_FRIOSDB_FRIOSDB_ENDPOINT
    username: friosdb_WPROD
    password: DB_MYSQL_DESAENV04_FRIOSDB_FRIOSDB_WPROD
    initialization-mode: always



jwt:
  secret: ${SECRET_TOKEN}
  expiration: 86400000